apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
        - name: messaging-container
          image: your-dockerhub-username/django-messaging:2.0
          ports:
            - containerPort: 8000
