#!/bin/bash
# Scale Django app and monitor

echo "Scaling Django app to 3 replicas..."
kubectl scale deployment django-messaging-app --replicas=3

echo "Verifying running pods..."
kubectl get pods -l app=messaging-app

echo "Running load test with wrk..."
wrk -t4 -c100 -d30s http://<service-cluster-ip>:8000/

echo "Monitoring resource usage..."
kubectl top pods
