#!/bin/bash
# Rolling update script

echo "Applying updated deployment..."
kubectl apply -f messaging_app/blue_deployment.yaml

echo "Monitoring rollout status..."
kubectl rollout status deployment/messaging-blue

echo "Testing app for downtime..."
while true; do
  curl -s -o /dev/null -w "%{http_code}\n" http://<service-cluster-ip>:8000/
  sleep 1
done &

sleep 20
pkill curl

echo "Verifying updated pods..."
kubectl get pods -l app=messaging-app,version=blue