apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging-app
    version: blue  # Change to green when switching
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
